name: ESLint & Prettier

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    name: ESLint & Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint & Prettier
        run: npm run lint
